app_mailing/urls.py
from django.urls import path

from app_mailing import views

app_name = 'app_mailing'

urlpatterns = [
    path('', views.index, name='index'),
    path('mailing/', views.MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>', views.MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/delete/<int:pk>', views.MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/create/', views.MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>', views.MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_try/<int:pk>', views.MailingTryListView.as_view(), name='mailing_try_list'),

    path('mailing/message/', views.MessageListView.as_view(), name='message_list'),
    path('mailing/message/create/', views.MessageCreateView.as_view(), name='message_create'),
    path('mailing/message/update/<int:pk>', views.MessageUpdateView.as_view(), name='message_update'),
    path('mailing/message/delete/<int:pk>', views.MessageDeleteView.as_view(), name='message_delete'),

    path('mailing/client/', views.ClientListView.as_view(), name='client_list'),
    path('mailing/client/create/', views.ClientCreateView.as_view(), name='client_create'),
    path('mailing/client/update/<int:pk>', views.ClientUpdateView.as_view(), name='client_update'),
    path('mailing/client/delete/<int:pk>', views.ClientDeleteView.as_view(), name='client_delete'),
]

app_manager/urls.py
from django.urls import path

from app_manager import views


app_name = 'app_manager'

urlpatterns = [
    path('mailings/', views.ManagerMailingListView.as_view(), name='mailing_list'),
    path('mailings/stop_mailing/<int:pk>', views.stop_mailing_view, name='stop_mailing'),
    path('clients/', views.ManagerClientListView.as_view(), name='client_list'),
    path('clients/ban_user/<int:pk>', views.ban_user_view, name='ban_user'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_mailing.urls', namespace='app_mailing')),
    path('users/', include('app_users.urls', namespace='app_users')),
    path('blog/', include('app_blog.urls', namespace='app_blog')),
    path('manager/', include('app_manager.urls', namespace='app_manager')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_manager/models.py
from django.db import models

# Create your models here.

app_manager/views.py
from django.shortcuts import redirect
from django.views import generic

from app_mailing.models import Mailing
from app_users.models import User


class ManagerMailingListView(generic.ListView):
    """Manager can view all existing mailings."""
    model = Mailing
    template_name = 'app_manager/mailing_list.html'


def stop_mailing_view(request, pk):
    """Manager can stop mailing."""
    mailing = Mailing.objects.get(pk=pk)
    mailing.status = 'stopped'
    mailing.save()
    return redirect('app_manager:mailing_list')


class ManagerClientListView(generic.ListView):
    """Manager can view all existing users."""
    model = User
    template_name = 'app_manager/client_list.html'


def ban_user_view(request, pk):
    """Manager can ban user."""
    user = User.objects.get(pk=pk)
    user.is_active = False
    user.save()
    return redirect('app_manager:client_list')

app_manager/templates/app_manager/client_list.html
{% extends 'app_mailing/base.html' %}

{% block title %}Клиенты{% endblock %}

{% block content %}

{% include 'app_manager/includes/inc_mailing_navbar.html' %}

<div class="container">
<div class="gap-2 mb-4 d-flex align-items-center justify-content-center">
  <a href="{% url 'app_mailing:client_create' %}">
      <button class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" type="button">
        Создать клиента
      </button>
  </a>
</div>
</div>

<div class="container">

<div class="row mb-3 text-center">
    {% for object in object_list %}
      <div class="col-4 themed-grid-col">{{ object.email }}

      <a href="{% url 'app_manager:ban_user' object.pk %}" title="Удалить" style="text-decoration: none;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
              <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
            </svg>
      </a>
      </div>
      <div class="col-4 themed-grid-col">Активен: {{ object.is_active }}</div>
      <div class="col-4 themed-grid-col">{{ object.first_name }}</div>
    {% endfor %}
    </div>

</div>


{% endblock %}

app_manager/templates/app_manager/mailing_list.html
{% extends 'app_mailing/base.html' %}

{% block title %}Рассылки{% endblock %}

{% block content %}

{% include 'app_manager/includes/inc_mailing_navbar.html' %}

<div class="container">
<div class="gap-2 mb-4 d-flex align-items-center justify-content-center">
</div>
</div>

<div class="row mb-3">
  {% for object in object_list %}
    <div class="col-md-4">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{ object.name }}</h3>
          <div class="mb-1 text-body-secondary">{{ с.time }}</div>
          <p class="card-text mb-auto">
            {% if object.periodicity == 'day' %}
            Раз в день
            {% elif object.periodicity == 'week' %}
            Раз в неделю
            {% else %}
            Раз в месяц
            {% endif %}
          </p>

          {% if object.status == 'created' %}
          <p class="card-text mb-auto" style="color: grey;">Создана</p>
          {% elif object.status == 'launched' %}
          <p class="card-text mb-auto" style="color: green;">Активна</p>
          {% else %}
          <p class="card-text mb-auto" style="color: red;">Завершена</p>
          {% endif %}
          <p class="card-text mb-auto"">Создатель: {{ object.author }}</p>

          <h5>{{ object.message.title }}</h5>
          <text>{{ object.message.body }}</text>

          <a href="{% url 'app_manager:stop_mailing' object.pk %}" class="icon-link gap-1 icon-link-hover" style="color: red;">
            Остановить рассылку
          </a>


        </div>

      </div>
    </div>
  {% endfor %}
  </div>


{% endblock %}