app_blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_blog import views


app_name = 'app_blog'


urlpatterns = [
    path('', cache_page(60)(views.BlogListView.as_view()), name='blog_list'),
    path('post/<int:pk>', views.BlogDetailView.as_view(), name='blog_detail'),
]

app_mailing/urls.py
from django.urls import path

from app_mailing import views

app_name = 'app_mailing'

urlpatterns = [
    path('', views.index, name='index'),
    path('mailing/', views.MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>', views.MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/delete/<int:pk>', views.MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/create/', views.MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>', views.MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_try/<int:pk>', views.MailingTryListView.as_view(), name='mailing_try_list'),

    path('mailing/message/', views.MessageListView.as_view(), name='message_list'),
    path('mailing/message/create/', views.MessageCreateView.as_view(), name='message_create'),
    path('mailing/message/update/<int:pk>', views.MessageUpdateView.as_view(), name='message_update'),
    path('mailing/message/delete/<int:pk>', views.MessageDeleteView.as_view(), name='message_delete'),

    path('mailing/client/', views.ClientListView.as_view(), name='client_list'),
    path('mailing/client/create/', views.ClientCreateView.as_view(), name='client_create'),
    path('mailing/client/update/<int:pk>', views.ClientUpdateView.as_view(), name='client_update'),
    path('mailing/client/delete/<int:pk>', views.ClientDeleteView.as_view(), name='client_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_mailing.urls', namespace='app_mailing')),
    path('users/', include('app_users.urls', namespace='app_users')),
    path('blog/', include('app_blog.urls', namespace='app_blog')),
    path('manager/', include('app_manager.urls', namespace='app_manager')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_mailing/models.py
from django.db import models

from app_users.models import User


NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Client for mailing(recepient)."""
    email = models.EmailField(max_length=50, verbose_name='почта')
    full_name = models.CharField(max_length=128, verbose_name='фио')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Создатель')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    """Mailing message that sends to users."""
    title = models.CharField(max_length=128, verbose_name='заголовок')
    body = models.TextField(verbose_name='тело сообщения')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Создатель')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Mailing(models.Model):
    """Mailing settings."""
    PERIODICITY_CHOICES = [
        ('day', 'раз в день'),
        ('week', 'раз в неделю'),
        ('month', 'раз в месяц')
    ]
    PERIODICITY_STATUS = [
        ('stopped', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена')
    ]

    name = models.CharField(max_length=50, verbose_name='имя рассылки')
    time = models.TimeField(verbose_name='время рассылки')
    periodicity = models.CharField(max_length=5,
                                   choices=PERIODICITY_CHOICES,
                                   verbose_name='периодичность')
    status = models.CharField(max_length=8,
                              choices=PERIODICITY_STATUS,
                              verbose_name='статус', default='created')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Создатель')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение')
    recipients = models.ManyToManyField(Client, verbose_name='клиенты')

    def __str__(self):
        return f'{self.name}--{self.time}--{self.periodicity}--{self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class MailingTry(models.Model):
    """Mailing try."""
    MAILING_TRY_STATUS = [
        ('OK', 'Выполнено'),
        ('Err', 'Ошибка')
    ]

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    try_datetime = models.DateTimeField(auto_now_add=True, verbose_name='время попытки')
    try_status = models.CharField(max_length=3,
                                  choices=MAILING_TRY_STATUS,
                                  verbose_name='статус')
    mail_service_response = models.TextField(verbose_name='ответ почтового сервиса')

    def __str__(self):
        return f'{self.try_datetime}--{self.try_status}--{self.mailing}: {self.mail_service_response}'

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'

app_mailing/forms.py
from django import forms

from app_mailing.models import Mailing, Message, Client


class MailingForm(forms.ModelForm):
    """Form for mailing create/update."""
    class Meta:
        model = Mailing
        exclude = ['author']


class MessageForm(forms.ModelForm):
    """Form for message create/update."""
    class Meta:
        model = Message
        exclude = ['author']


class ClienteForm(forms.ModelForm):
    """Form for client create/update."""
    class Meta:
        model = Client
        exclude = ['author']

app_mailing/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from app_mailing.forms import MailingForm, MessageForm, ClienteForm
from app_mailing.models import Mailing, Message, MailingTry, Client
from app_blog.models import BlogPost
from services.cached_data import get_cached_index_data


def index(request):
    """Main page with statistics."""
    all_mailing_counter, active_mailing_counter, unique_client_counter, random_blogposts = get_cached_index_data()

    context = {
        'all_mailing_counter': all_mailing_counter,
        'active_mailing_counter': active_mailing_counter,
        'unique_client_counter': unique_client_counter,
        'random_blogposts': random_blogposts,
    }
    return render(request, template_name='app_mailing/index.html', context=context)


class MailingListView(LoginRequiredMixin, generic.ListView):
    """User can view his mailings."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Mailing
    template_name = 'app_mailing/mailing_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(author=self.request.user)
        return queryset


class MailingDetailView(LoginRequiredMixin, generic.DetailView):
    """User can view details about his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Mailing
    template_name = 'app_mailing/mailing_detail.html'


class MailingDeleteView(LoginRequiredMixin, generic.DeleteView):
    """User can delete his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Mailing
    success_url = reverse_lazy('app_mailing:mailing_list')
    template_name = 'app_mailing/mailing_delete.html'


class MailingCreateView(LoginRequiredMixin, generic.CreateView):
    """User can create new mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Mailing
    template_name = 'app_mailing/mailing_create.html'
    form_class = MailingForm
    success_url = reverse_lazy('app_mailing:mailing_list')

    def form_valid(self, form):
        if form.is_valid():
            new_form = form.save()
            new_form.author = self.request.user
            new_form.save()
        return super().form_valid(form)

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['message'].queryset = Message.objects.filter(
            author=self.request.user
        )
        form.fields['recipients'].queryset = Client.objects.filter(
            author=self.request.user
        )
        return form


class MailingUpdateView(LoginRequiredMixin, generic.UpdateView):
    """USer can update his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Mailing
    template_name = 'app_mailing/mailing_create.html'
    form_class = MailingForm
    success_url = reverse_lazy('app_mailing:mailing_list')


class MailingTryListView(LoginRequiredMixin, generic.ListView):
    """User can view statistic about his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = MailingTry
    template_name = 'app_mailing/mailing_try_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = MailingTry.objects.filter(mailing=self.kwargs.get('pk')).order_by('-try_datetime')
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailing'] = Mailing.objects.get(pk=self.kwargs.get('pk'))
        return context_data


class MessageListView(LoginRequiredMixin, generic.ListView):
    """User can view his created messages for mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Message
    template_name = 'app_mailing/message_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(author=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, generic.CreateView):
    """User can create new message for his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Message
    template_name = 'app_mailing/message_create.html'
    form_class = MessageForm
    success_url = reverse_lazy('app_mailing:message_list')

    def form_valid(self, form):
        if form.is_valid():
            new_form = form.save()
            new_form.author = self.request.user
            new_form.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, generic.UpdateView):
    """User can update message for his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Message
    template_name = 'app_mailing/message_create.html'
    form_class = MessageForm
    success_url = reverse_lazy('app_mailing:message_list')


class MessageDeleteView(LoginRequiredMixin, generic.DeleteView):
    """User can delete message for his mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Message
    success_url = reverse_lazy('app_mailing:message_list')
    template_name = 'app_mailing/message_delete.html'


class ClientListView(LoginRequiredMixin, generic.ListView):
    """User can view his clients."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Client
    template_name = 'app_mailing/client_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(author=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, generic.CreateView):
    """User can create new clients for mailing."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Client
    template_name = 'app_mailing/client_create.html'
    form_class = ClienteForm
    success_url = reverse_lazy('app_mailing:client_list')

    def form_valid(self, form):
        if form.is_valid():
            new_form = form.save()
            new_form.author = self.request.user
            new_form.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, generic.UpdateView):
    """User can update clients."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Client
    template_name = 'app_mailing/client_update.html'
    form_class = ClienteForm
    success_url = reverse_lazy('app_mailing:client_list')


class ClientDeleteView(LoginRequiredMixin, generic.DeleteView):
    """User can delete clients."""
    login_url = reverse_lazy('app_users:login')
    redirect_field_name = "redirect_to"

    model = Client
    success_url = reverse_lazy('app_mailing:client_list')
    template_name = 'app_mailing/client_delete.html'

app_mailing/templates/app_mailing/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'app_mailing/includes/inc_header.html' %}

{% block content %}{% endblock %}

{% include 'app_mailing/includes/inc_footer.html' %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

app_mailing/templates/app_mailing/client_create.html
{% extends 'app_mailing/base.html' %}

{% block title %}Создание клиента{% endblock %}

{% block content %}


<form method="post" >
{% csrf_token %}
{{ form.as_p }}
<button type="submit" value="Save">Сохранить</button>
</form>

{% endblock %}

app_mailing/templates/app_mailing/client_delete.html
{% extends 'app_mailing/base.html' %}

{% block title %}Удалить {{ object.email }}?{% endblock %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Удалить {{ object.name }}?</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">После удаления данные восстановить невозможно!</p>
      <p class="lead mb-4">Вы уверены?</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'app_mailing:client_list' %}"><button type="submit" value="Reject" class="btn btn-primary btn-lg px-4 gap-3">Не удалять</button></a>
        <form method="post">
          {% csrf_token %}
          <button type="submit" value="Confirm" class="btn btn-outline-danger btn-lg px-4">Удалить</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

app_mailing/templates/app_mailing/client_list.html
{% extends 'app_mailing/base.html' %}

{% block title %}Клиенты{% endblock %}

{% block content %}

{% include 'app_mailing/includes/inc_mailing_navbar.html' %}

<div class="container">
<div class="gap-2 mb-4 d-flex align-items-center justify-content-center">
  <a href="{% url 'app_mailing:client_create' %}">
      <button class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" type="button">
        Создать клиента
      </button>
  </a>
</div>
</div>

<div class="container">

<div class="row mb-3 text-center">
    {% for object in object_list %}
      <div class="col-4 themed-grid-col">{{ object.email }}
      <a href="{% url 'app_mailing:client_update' object.pk %}" title="Изменить" style="text-decoration: none;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
      </a>
      <a href="{% url 'app_mailing:client_delete' object.pk %}" title="Удалить" style="text-decoration: none;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
              <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
            </svg>
      </a>
      </div>
      <div class="col-4 themed-grid-col">{{ object.full_name }}</div>
      <div class="col-4 themed-grid-col">{{ object.comment }}</div>
    {% endfor %}
    </div>

</div>


{% endblock %}

app_mailing/templates/app_mailing/client_update.html
{% extends 'app_mailing/base.html' %}

{% block title %}{{ object.email }}{% endblock %}

{% block content %}


<form method="post" >
{% csrf_token %}
{{ form.as_p }}
<button type="submit" value="Save">Сохранить</button>
</form>

{% endblock %}

app_mailing/templates/app_mailing/index.html
{% extends 'app_mailing/base.html' %}

{% load mediapath %}

{% block title %}Главная{% endblock %}


{% block content %}
<div class="container px-4 py-5" id="hanging-icons">
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">

        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Созданных рассылок: {{ all_mailing_counter }} </h3>

        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">

        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Активных рассылок: {{ active_mailing_counter }}</h3>

        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">

        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Уникальных клиентов: {{ unique_client_counter }}</h3>

        </div>
      </div>
    </div>
  </div>

{% if random_blogposts %}
{% for object in random_blogposts %}
<div class="container">
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary" style="background: linear-gradient(rgba(255, 255, 255, 0.3), rgba(0, 0, 0, 0.8)), url({% mediapath object.image %});; background-size: cover;">

    <div class="col-lg-6 px-0" style="color: white;">
      <h1 class="display-4 fst-italic">{{ object.title }}</h1>
      <p class="lead my-3">{{ object.text|truncatechars:300 }}</p>
        <br>
      <p class="my-1 small">Просмотров: {{ object.view_counter }}</p>
      <p class="my-1 small">Создано: {{ object.publication_date }}</p>
      <p class="lead mb-0"><a href="{% url 'app_blog:blog_detail' object.pk %}" class="text-body-white fw-bold" style="color: white;">Читать...</a></p>
    </div>

  </div>
</div>
{% endfor %}
{% endif %}

{% endblock %}

app_mailing/templates/app_mailing/mailing_create.html
{% extends 'app_mailing/base.html' %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}


<form method="post" >
{% csrf_token %}
{{ form.as_p }}
<button type="submit" value="Save">Сохранить</button>
</form>

{% endblock %}

app_mailing/templates/app_mailing/mailing_delete.html
{% extends 'app_mailing/base.html' %}

{% block title %}Удалить {{ object.name }}?{% endblock %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Удалить {{ object.name }}?</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">После удаления данные восстановить невозможно!</p>
      <p class="lead mb-4">Вы уверены?</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'app_mailing:mailing_detail' object.pk %}"><button type="submit" value="Reject" class="btn btn-primary btn-lg px-4 gap-3">Не удалять</button></a>
        <form method="post">
          {% csrf_token %}
          <button type="submit" value="Confirm" class="btn btn-outline-danger btn-lg px-4">Удалить</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

app_mailing/templates/app_mailing/mailing_detail.html
{% extends 'app_mailing/base.html' %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">{{ object.name }}</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-2"><strong>Время рассылки:</strong> {{ object.time }}</p>
      <p class="lead mb-2"><strong>Периодичность:</strong>
            {% if object.periodicity == 'day' %}
            Раз в день
            {% elif object.periodicity == 'week' %}
            Раз в неделю
            {% else %}
            Раз в месяц
            {% endif %}
      </p>
      <p class="lead mb-2"><strong>Статус:</strong>
          {% if object.status == 'created' %}
          <span class="card-text mb-auto" style="color: grey;">Создана</span>
          {% elif object.status == 'launched' %}
          <span class="card-text mb-auto" style="color: green;">Активна</span>
          {% else %}
          <span class="card-text mb-auto" style="color: red;">Завершена</span>
          {% endif %}
      </p>

      <p class="lead mb-2"><strong>Заголовок сообщения:</strong> {{ object.message.title }}</p>
      <p class="lead mb-2"><strong>Тело сообщения:</strong> {{ object.message.body }}</p>
      <p class="lead mb-2"><strong>Получатели:</strong> {{ object.recipients.all|join:", " }}</p>
      <br>



      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <a href="{% url 'app_mailing:mailing_update' object.pk %}"><button type="button" class="btn btn-primary btn-lg px-4 gap-3">Изменить</button></a>
          <a href="{% url 'app_mailing:mailing_delete' object.pk %}"><button type="button" class="btn btn-outline-danger btn-lg px-4">Удалить</button></a>
      </div>
    </div>
  </div>


{% endblock %}

app_mailing/templates/app_mailing/mailing_try_list.html
{% extends 'app_mailing/base.html' %}

{% block title %}Статистика рассылки{% endblock %}

{% include 'app_mailing/includes/inc_mailing_navbar.html' %}

{% block content %}
<div class="container">
<h2 class="mt-4">Статистика для рассылки: {{ mailing.name }}</h2>
</div>
{% if object_list %}
{% for object in object_list %}

<div class="container">
<div class="row mb-3 text-center">
      <div class="col-4 themed-grid-col">{{ object.try_datetime }}</div>
      <div class="col-4 themed-grid-col">{{ object.try_status }}</div>
      <div class="col-4 themed-grid-col">{{ object.mail_service_response }}</div>
    </div>
</div>

{% endfor %}
{% else %}
<div class="container">
    <p class="mt-4">Рассылка не проводилась ни разу</p>
</div>


{% endif %}

{% endblock %}

app_mailing/templates/app_mailing/mailing_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app_mailing/templates/app_mailing/message_create.html
{% extends 'app_mailing/base.html' %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}


<form method="post" >
{% csrf_token %}
{{ form.as_p }}
<button type="submit" value="Save">Сохранить</button>
</form>

{% endblock %}

app_mailing/templates/app_mailing/message_delete.html
{% extends 'app_mailing/base.html' %}

{% block title %}Удалить {{ object.name }}?{% endblock %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Удалить {{ object.name }}?</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">После удаления данные восстановить невозможно!</p>
      <p class="lead mb-4">Вы уверены?</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'app_mailing:message_list' %}"><button type="submit" value="Reject" class="btn btn-primary btn-lg px-4 gap-3">Не удалять</button></a>
        <form method="post">
          {% csrf_token %}
          <button type="submit" value="Confirm" class="btn btn-outline-danger btn-lg px-4">Удалить</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

app_mailing/templates/app_mailing/message_list.html
{% extends 'app_mailing/base.html' %}

{% block title %}Письма{% endblock %}

{% block content %}

{% include 'app_mailing/includes/inc_mailing_navbar.html' %}

<div class="container">
<div class="gap-2 mb-4 d-flex align-items-center justify-content-center">
  <a href="{% url 'app_mailing:message_create' %}">
      <button class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" type="button">
        Создать письмо
      </button>
  </a>
</div>
</div>

<div class="row mb-3">
  {% for object in object_list %}
    <div class="col-md-4">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{ object.title }}</h3>
          <p class="card-text mb-auto">{{ object.body }}</p>
          <a href="{% url 'app_mailing:message_update' object.pk %}" class="icon-link gap-1 icon-link-hover">
            Изменить
            <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
          </a>
          <a href="{% url 'app_mailing:message_delete' object.pk %}" class="icon-link gap-1 icon-link-hover" style="color: red;">
            Удалить
            <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
          </a>

        </div>

      </div>
    </div>
  {% endfor %}
  </div>


{% endblock %}