app_users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from app_users import views


app_name = 'app_users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='app_users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('register/confirmation/', views.UserRegisterConfirmationView.as_view(), name='register_confirmation'),
    path('verify/<int:code>', views.verify_view, name='verify'),
    path('recover_password/', views.recover_password_view, name='recover_password'),
    path('recover_password_confirmation/', views.RecoverPasswordConfirmationView.as_view(), name='recover_password_confirmation')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_mailing.urls', namespace='app_mailing')),
    path('users/', include('app_users.urls', namespace='app_users')),
    path('blog/', include('app_blog.urls', namespace='app_blog')),
    path('manager/', include('app_manager.urls', namespace='app_manager')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """Redefine existing User model."""
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    first_name = models.CharField(max_length=50, verbose_name='имя')
    last_name = models.CharField(max_length=50, verbose_name='фамилия')
    surname = models.CharField(max_length=50, verbose_name='отчество')

    is_active = models.BooleanField(default=False, verbose_name='активен')
    verify_code = models.CharField(max_length=4, verbose_name='код подтверждения', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from app_users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class RecoverPasswordForm(forms.Form):
    email = forms.EmailField(required=True)

app_users/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from app_users.models import User
from app_users.forms import UserRegisterForm, RecoverPasswordForm
from services.email import get_verification_code, send_registration_email
from services.recover_password import user_set_random_password


class UserRegisterView(generic.CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'app_users/register.html'
    success_url = reverse_lazy('app_users:register_confirmation')

    def form_valid(self, form):
        """Send verification code after registration."""
        if form.is_valid():
            new_form = form.save()
            new_form.verify_code = get_verification_code()

            send_registration_email(new_form.email, new_form.verify_code)

            new_form.save()
        return super().form_valid(form)


class UserRegisterConfirmationView(generic.TemplateView):
    template_name = 'app_users/register_confirmation.html'


def verify_view(request, code):
    """Verify user profile and makes it active."""
    user = User.objects.get(verify_code=str(code))
    user.is_active = True
    user.verify_code = 'NULL'
    user.save()
    return redirect('app_users:login')


def recover_password_view(request):
    """User forget password page. Can set another password to user. And send email with new password."""
    if request.method == 'POST':
        recover_form = RecoverPasswordForm(request.POST)
        if recover_form.is_valid():
            email = recover_form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)

                user_set_random_password(user)

                return redirect('app_users:recover_password_confirmation')
            except ObjectDoesNotExist:
                form = RecoverPasswordForm()
                context = {'form': form,
                           'user_does_not_exists': recover_form.cleaned_data['email']}
                return render(request, 'app_users/recover_password.html', context=context)
    else:
        form = RecoverPasswordForm()
        context = {'form': form}
        return render(request, 'app_users/recover_password.html', context=context)


class RecoverPasswordConfirmationView(generic.TemplateView):
    template_name = 'app_users/recover_password_confirmation.html'

app_users/templates/app_users/login.html
{% extends 'app_mailing/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">Войти</input>
    </form>
</div>
<a href="{% url 'app_users:recover_password' %}">Забыли пароль?</a>

{% endblock %}

app_users/templates/app_users/recover_password.html
{% extends 'app_mailing/base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
{% if user_does_not_exists %}
<p>Пользователь с email {{ user_does_not_exists }} не существует!</p>
{% endif %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">Восстановить пароль</input>
    </form>
</div>

{% endblock %}

app_users/templates/app_users/recover_password_confirmation.html
{% extends 'app_mailing/base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
<h3>Восстановление пароля</h3>
<p>Новый пароль был выслан Вам на почту. Войдите при помощи него</p>
<a href="{% url 'app_users:login' %}">Перейти на страницу входа</a>
{% endblock %}

app_users/templates/app_users/register.html
{% extends 'app_mailing/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">Готово</input>
    </form>
</div>


{% endblock %}

app_users/templates/app_users/register_confirmation.html
{% extends 'app_mailing/base.html' %}

{% block title %}Регистрация выполнена{% endblock %}

{% block content %}
<h3>Регистрация выполнена</h3>
<p>Теперь для подтверждения почты необходимо перейти по письму, которое мы выслали на Ваш e-mail.</p>
{% endblock %}